name: Build

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "*.md"
      - ".vscode"
      - ".nova"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "*.md"
      - ".vscode"
      - ".nova"

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_14.3.app && /usr/bin/xcodebuild -version
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
