name: Docs

on:
  workflow_dispatch:

jobs:
  make-docs:
    strategy:
      matrix:
        os: [macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: make docs
        run: make docs
      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: docs
          create_branch: true
          push_options: "--force"
